name: secret scan

on :
    workflow_call:
jobs:
    secret_scan-trufflehog:
        name: Run Trufflehog Scan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0 # Fetches all history so Trufflehog can scan entire commit histories

            - name: Trufflehog OSS Scan
              uses: trufflesecurity/trufflehog@main
              with:
                path: ./
                base: ${{ github.event.repository.default_branch }}
                head: HEAD
                extra_args: --debug --only-verified # Optional: checks if the secret is still active
