name: dependency scan

on:
    workflow_call:

jobs:
    code-dependency_scan:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false #true if any fail stop the job
            matrix:
                python-version: ["3.13"] #, "3.12", "3.11"
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
              
            - name: setup python ${{matrix.python-version}}
              uses: actions/setup-python@v5
              with:
                python-version: ${{matrix.python-version}}
                
            - name: install dependencies
              run: pip install -r requirements.txt

            # Run Safety to check for vulnerable dependencies deprecated in the current codebase
            #- name: Run Safety to check for vulnerable dependencies
             # run: safety check --full-report  

            
            - name: Run pip-audit to check for vulnerable dependencies
              run: pip-audit --verbose