name: END to END DevSecOps pipeline

on:
    push:
        branches: [main]

jobs:
    code-quality:
        uses: ./.github/workflows/11-1-code-quality.yml
    secret-scan:
        uses: ./.github/workflows/11-2-secret-scan.yml
    dependency-scan:
        uses: ./.github/workflows/11-3-dependency-scan.yml
    docker-lint:
        uses: ./.github/workflows/11-4-docker-lint.yml



    