name : deploy to production
on:
    workflow_call:

jobs:
    deploy-on-ec2-prod:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v4
              with:
                #registry: docker.io or ghcr.io or any other registry with the url - If not set then will default to Docker Hub
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}


            - name: SSH to Prod server & create app folder if not exists and install docker
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USER }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                script: |
                 echo "Installing required packages & folders"
                 sudo apt-get update && sudo apt-get install docker.io docker-compose-v2 -y
                 sudo usermod -aG docker $USER
                 mkdir -p devops

            - name: Copy the docker-compose file
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USER }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                source: docker-compose.yml
                target: ~/devops
                
            - name: SSH to Prod server & run the app
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USER }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                script: |
                 echo "Running App"
                 export DOCKERHUB_USERNAME=${{ vars.DOCKERHUB_USERNAME }}
                 export DOCKER_TAG=${{ github.sha }}
                 echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ vars.DOCKERHUB_USERNAME }} --password-stdin
                 cd ~/devops && docker compose down && docker compose up -d --build --force-recreate --pull always