name: END to END DevSecOps pipeline

on:
    push:
        branches: [main]

jobs:
    code-quality:
        uses: ./.github/workflows/11-1-code-quality.yml
    secret-scan:
        uses: ./.github/workflows/11-2-secret-scan.yml
    dependency-scan:
        uses: ./.github/workflows/11-3-dependency-scan.yml
    docker-lint:
        uses: ./.github/workflows/11-4-docker-lint.yml
    docker-build-push:
        needs: [code-quality,secret-scan,dependency-scan,docker-lint]
        uses: ./.github/workflows/11-5-docker-build-push-hub.yml
        secrets: inherit # To pass secrets from this workflow to the called workflow like dockerhub token for pushing the image

    trivy-image-scan:
        needs: docker-build-push
        uses: ./.github/workflows/11-6-trivy-image-scan.yml
        secrets: inherit # To pass secrets from this workflow to the called workflow like dockerhub token for scanning the image



    