name: custom paths is changes then run
on:
  push:
    branches:  #if any changes happen in given paths then automatically run the job else manually approve it.
      - main
    paths:
      - "**.html"
      - '**.yml'
  workflow_dispatch:
jobs:
  index_html_change_run:
    runs-on: ubuntu-latest
    steps:
      - name: after changing index.html file this job will run
        run: echo "after changing index.html file this job will run yessssssssss" #orignal commands not added yet this is for practice only
      
