name: CICD_without_orignal_comnmands

on: 
  workflow_dispatch:
    inputs:
      environment:
      description: which env you have to build please select from below
      default: "dev"
      required: true
      type: choice
        options:
          - dev
          - stage
          - prod
      

jobs:
  code: #this is job name
    runs-on: ubuntu-latest # this is runner
    steps: #steps inside code job and runner and same for all below job names build test deploy
      - name: get the code
        run: echo "git pull to get code" #orignal commands not added yet this is for practice only
        
  build:
      runs-on: ubuntu-latest
      steps:
        - name: build the code
          run: echo "mavne build" #orignal commands not added yet this is for practice only
  test:
      runs-on: ubuntu-latest
      steps:
        - name: test using tivy or jemeter junit
          run: echo "testing commands" #orignal commands not added yet this is for practice only
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: deploy the code on server
          run: echo "deploy the code on server ec2 or cloud" #orignal commands not added yet this is for practice only
