---
name: Vishal Hello
on:
  push:
    branches: 
        main
jobs:
  hello_i_am_job_name:
    runs-on: ubuntu-latest
    steps:
       - name: my name is what
         run: echo "Vishal wagh on ubuntu $USER"
  versions:
    runs-on: ubuntu-latest
    steps:
      - name: version of docekr and python
        run: docker --version && python --version
